#define BUILD_COMMIT_ID "613cf98-dirty"
#define PROJECT_VERSION "1.4.5"
#define PROJECT_VERSION_BUILD_NO "750"
#define PROJECT_VERSION_LONG PROJECT_VERSION "." PROJECT_VERSION_BUILD_NO " (" BUILD_COMMIT_ID ")"
